from frog_classes import index_display_html_card

def get_index_body(header, tagline, summary, topic,cards):
    body = f"""
    <body>
  <main>
    <header>
      <p class="eyebrow">{header}</p>
      <h1>{tagline}</h1>
      <p>{summary}</p>
    </header>

    <nav id="topics" class="topics">
"""
    count = 0
    for card in cards:
        count += 1
        body += f"""
            <a class="card" href="{card.link}">
                <span class="number">{count:02d} <span id=complete-{card.link}></span></span>
                <h2>{card.title}</h2>
                <p>{card.summary}</p>
                <span class="read-more">Explore topic <span class="arrow" aria-hidden="true">→</span></span>
            </a>
            """
    body += """
    <footer>Generated by AI, take care not to trust blindly.</footer>
  </main>
</body>
</html>
    """

    #javascript
    body += """
<script>
    /*
 * Completion Stuff
 */
 
 function lessonIdFromHref(href) {
        try {
            const path = new URL(href, window.location.href).pathname;
            const filename = path.split("/").pop();
            if (!filename || !filename.endsWith(".html") || filename === "index.html") return null;
            return filename.slice(0, -5);
        } catch {
            return null;
        }
    }
    
    async function getCompletionState(lesson_id){
    
        try{
        const response = await fetch("/api/completions", {cache: "no-store"});
            const data = await response.json();
            if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
            completionState = data.lessons || {};
            const state = completionState[lesson_id];
            return Boolean(state.complete)
        }
        catch(error){
            console.error("Could not load lesson completion state", error);
        }
    
    }
    
    async function refreshCompletionStatus(link){
        lesson_id = lessonIdFromHref(link)
        complete = await getCompletionState(lesson_id);
        const isCompleteSpan = document.getElementById("complete-"+link);
        if (complete === true) {
            isCompleteSpan.innerHTML = "Complete"
        }
        else{
            isCompleteSpan.innerHTML = 'Incomplete'
        }
    }
    
    window.addEventListener("load", function () {
    const topics = document.getElementById("topics");
    const cards = topics.querySelectorAll(".card");
    cards.forEach(card => {
        refreshCompletionStatus(card.getAttribute("href"));
        });
    });
    
</script>
    """


    return body


def get_index_head(title):
    head = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>__TITLE__</title>
  <style>
    :root {
      color-scheme: dark;
      --background: #090d14;
      --surface: #111824;
      --surface-hover: #172131;
      --text: #edf4ff;
      --muted: #9cabc0;
      --accent: #55d6be;
      --accent-soft: rgba(85, 214, 190, 0.12);
      --border: rgba(255, 255, 255, 0.09);
      --shadow: rgba(0, 0, 0, 0.3);
    }

    * {
      box-sizing: border-box;
    }

    html {
      scroll-behavior: smooth;
    }

    body {
      min-height: 100vh;
      margin: 0;
      background:
        radial-gradient(circle at 15% 0%, rgba(85, 214, 190, 0.1), transparent 28rem),
        radial-gradient(circle at 90% 15%, rgba(87, 126, 255, 0.1), transparent 30rem),
        var(--background);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.6;
    }

    main {
      width: min(1120px, calc(100% - 2rem));
      margin: 0 auto;
      padding: 5rem 0;
    }

    header {
      max-width: 760px;
      margin-bottom: 3rem;
    }

    .eyebrow {
      display: inline-flex;
      align-items: center;
      gap: 0.55rem;
      margin: 0 0 1rem;
      color: var(--accent);
      font-size: 0.78rem;
      font-weight: 750;
      letter-spacing: 0.14em;
      text-transform: uppercase;
    }

    .eyebrow::before {
      width: 0.55rem;
      height: 0.55rem;
      border-radius: 50%;
      background: var(--accent);
      box-shadow: 0 0 1rem var(--accent);
      content: "";
    }

    h1 {
      margin: 0;
      font-size: clamp(2.4rem, 7vw, 4.8rem);
      line-height: 1.02;
      letter-spacing: -0.055em;
    }

    header p {
      max-width: 650px;
      margin: 1.4rem 0 0;
      color: var(--muted);
      font-size: clamp(1rem, 2.2vw, 1.15rem);
    }

    .topics {
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 1rem;
    }

    .card {
      position: relative;
      display: flex;
      min-height: 280px;
      flex-direction: column;
      overflow: hidden;
      padding: 1.65rem;
      border: 1px solid var(--border);
      border-radius: 1.25rem;
      background: linear-gradient(145deg, rgba(255, 255, 255, 0.035), transparent), var(--surface);
      color: inherit;
      text-decoration: none;
      box-shadow: 0 18px 45px var(--shadow);
      transition: transform 180ms ease, border-color 180ms ease, background-color 180ms ease;
    }

    .card::after {
      position: absolute;
      right: -4rem;
      bottom: -5rem;
      width: 11rem;
      height: 11rem;
      border-radius: 50%;
      background: var(--accent-soft);
      filter: blur(8px);
      content: "";
      transition: transform 180ms ease;
    }

    .card:hover {
      transform: translateY(-5px);
      border-color: rgba(85, 214, 190, 0.42);
      background-color: var(--surface-hover);
    }

    .card:hover::after {
      transform: scale(1.15);
    }

    .number {
      margin-bottom: 2rem;
      color: var(--accent);
      font-size: 0.8rem;
      font-weight: 750;
      letter-spacing: 0.12em;
    }

    h2 {
      max-width: 22ch;
      margin: 0;
      font-size: clamp(1.25rem, 3vw, 1.65rem);
      line-height: 1.22;
      letter-spacing: -0.025em;
    }

    .card p {
      position: relative;
      z-index: 1;
      margin: 1rem 0 1.75rem;
      color: var(--muted);
      font-size: 0.96rem;
    }

    .read-more {
      position: relative;
      z-index: 1;
      display: inline-flex;
      align-items: center;
      gap: 0.55rem;
      margin-top: auto;
      color: var(--accent);
      font-size: 0.9rem;
      font-weight: 700;
    }

    .arrow {
      transition: transform 180ms ease;
    }

    .card:hover .arrow {
      transform: translateX(0.3rem);
    }

    .card:focus-visible {
      outline: 3px solid var(--accent);
      outline-offset: 4px;
    }

    footer {
      margin-top: 2.5rem;
      color: #728096;
      font-size: 0.85rem;
    }

    @media (max-width: 720px) {
      main {
        padding: 3.5rem 0;
      }

      .topics {
        grid-template-columns: 1fr;
      }

      .card {
        min-height: 0;
      }
    }

    @media (prefers-reduced-motion: reduce) {
      *,
      *::before,
      *::after {
        scroll-behavior: auto !important;
        transition: none !important;
      }
    }
  </style>
</head>
    """
    return head.replace("__TITLE__",title)



def get_lesson_html(lesson):
    return f"""
<head>
    <link rel="stylesheet" href="style.css">
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
</head>
<p style="display: flex; justify-content: space-between;">
    <span id="isCompleteSpan"></span>
    <a href="./">Return to topic</a>
</p>
<h1>{lesson.title}</h1>
<blockquote>
{lesson.summary}
</blockquote>
<main id="lesson">
{lesson.content}
</main>
<div class="chat-header">
    <div>
        <div class="chat-title">Ask about this lesson</div>
        <div class="chat-subtitle">Questions stay focused on the current topic.</div>
    </div>
</div>
<div class="chat-messages" id="chatMessages">
    <div class="message assistant">
    </div>
</div>

<form class="chat-input-area" id="chatForm">
    <textarea
        id="chatInput"
        rows="2"
        placeholder="Ask a question..."
    ></textarea>

    <button type="submit" id="sendButton">
        Send
    </button>
</form>

    """ + """
<script>

/*
 * Apply markup parsing to the lesson content.
 */
const lesson_content = document.getElementById("lesson");
lesson_content.innerHTML = marked.parse(lesson_content.textContent);


const form = document.getElementById("chatForm");
const input = document.getElementById("chatInput");
const messages = document.getElementById("chatMessages");
const sendButton = document.getElementById("sendButton");

let conversation = [];
let waitingForResponse = false;


/*
 * Add a message bubble to the chat UI.
 */
function addMessage(text, role) {
    const message = document.createElement("div");
    message.className = `message ${role}`;

    const bubble = document.createElement("div");
    bubble.className = "message-bubble";
    bubble.innerHTML = text;

    message.appendChild(bubble);
    messages.appendChild(message);

    scrollToBottom();

    return message;
}


/*
 * Show a temporary "Thinking..." message while waiting
 * for the LLM response.
 */
function addTypingIndicator() {
    const message = document.createElement("div");
    message.className = "message assistant";
    message.id = "typingIndicator";

    const bubble = document.createElement("div");
    bubble.className = "message-bubble";
    bubble.textContent = "Thinking...";

    message.appendChild(bubble);
    messages.appendChild(message);

    scrollToBottom();
}


/*
 * Remove the temporary typing indicator.
 */
function removeTypingIndicator() {
    const indicator = document.getElementById("typingIndicator");

    if (indicator) {
        indicator.remove();
    }
}


/*
 * Scroll chat to newest message.
 */
function scrollToBottom() {
    //messages.scrollTop = messages.scrollHeight;
}


/*
 * Resize textarea as the user types.
 */
function resizeInput() {
    input.style.height = "auto";

    const maxHeight = 140;

    input.style.height =
        Math.min(input.scrollHeight, maxHeight) + "px";
}


/*
 * Enable/disable chat controls while a request is active.
 */
function setLoading(loading) {
    waitingForResponse = loading;
    sendButton.disabled = loading;

    if (loading) {
        sendButton.textContent = "Sending...";
    } else {
        sendButton.textContent = "Send";
    }
}


/*
 * Submit a question to the backend.
 */
async function askQuestion(question) {
    addMessage(question, "user");

    conversation.push({
        role: "user",
        content: question
    });

    input.value = "";
    resizeInput();

    setLoading(true);
    addTypingIndicator();

    try {
        const response = await fetch("/api/ask", {
            method: "POST",

            headers: {
                "Content-Type": "application/json"
            },

            body: JSON.stringify({
                question: question,

                // Send previous conversation so the backend
                // can preserve context if desired.
                messages: conversation,

                // Useful if each lesson has its own URL.
                lesson: window.location.pathname
            })
        });

        if (!response.ok) {
            let errorText;

            try {
                const errorData = await response.json();

                errorText =
                    errorData.error ||
                    errorData.message ||
                    `HTTP ${response.status}`;
            } catch {
                errorText = `HTTP ${response.status}`;
            }

            throw new Error(errorText);
        }

        const data = await response.json();

        if (!data.answer) {
            throw new Error(
                "The server returned no answer."
            );
        }

        removeTypingIndicator();

        let rendered_answer = marked.parse(data.answer);

        addMessage(
            rendered_answer,
            "assistant"
        );

        conversation.push({
            role: "assistant",
            content: data.answer
        });

    } catch (error) {
        console.error(
            "Chat request failed:",
            error
        );

        removeTypingIndicator();

        addMessage(
            `Sorry, I couldn't get an answer. ${error.message}`,
            "assistant"
        );

    } finally {
        setLoading(false);

        input.focus();

        scrollToBottom();
    }
}


/*
 * Form submission.
 */
form.addEventListener(
    "submit",
    async (event) => {
        event.preventDefault();

        if (waitingForResponse) {
            return;
        }

        const question =
            input.value.trim();

        if (!question) {
            return;
        }

        await askQuestion(question);
    }
);


/*
 * Enter sends.
 * Shift+Enter inserts a newline.
 */
input.addEventListener(
    "keydown",
    (event) => {
        if (
            event.key === "Enter" &&
            !event.shiftKey
        ) {
            event.preventDefault();

            form.requestSubmit();
        }
    }
);


/*
 * Auto-resize textarea while typing.
 */
input.addEventListener(
    "input",
    resizeInput
);


/*
 * Initial setup.
 */
resizeInput();
//input.focus();

/*
 * Completion Stuff
 */
 
 function lessonIdFromHref(href) {
        try {
            const path = new URL(href, window.location.href).pathname;
            const filename = path.split("/").pop();
            if (!filename || !filename.endsWith(".html") || filename === "index.html") return null;
            return filename.slice(0, -5);
        } catch {
            return null;
        }
    }
    
    async function getCompletionState(lesson_id){
    
        try{
        const response = await fetch("/api/completions", {cache: "no-store"});
            const data = await response.json();
            if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
            completionState = data.lessons || {};
            const state = completionState[lesson_id];
            return Boolean(state.complete)
        }
        catch(error){
            console.error("Could not load lesson completion state", error);
        }
    
    }
    
    async function refreshCompletionStatus(){
        lesson_id = lessonIdFromHref(window.location.href)
        complete = await getCompletionState(lesson_id);
        const isCompleteSpan = document.getElementById("isCompleteSpan");
        if (complete === true) {
            isCompleteSpan.innerHTML = "This lesson has been completed."
        }
        else{
            isCompleteSpan.innerHTML = 'This lesson not been marked complete. <button onClick="completeLesson()">Complete</button>'
        }
    }
    
    async function completeLesson(lessonId){
        lessonId = lessonIdFromHref(window.location.href)
        try{
            complete = true;
            const response = await fetch(`/api/lessons/${encodeURIComponent(lessonId)}/completion`, {
                method: "PUT",
                headers: {"Content-Type": "application/json"},
                body: JSON.stringify({complete})
            });
            const data = await response.json();
            if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
            refreshCompletionStatus()
        } catch (requestError) {
            checkbox.checked = previous;
            setContainerState(container, previous);
            error.textContent = `Could not save: ${requestError.message}`;
            }
    }


        
window.addEventListener("load", function () {
    refreshCompletionStatus()
});

</script>
"""

def get_index_css():
    return """
/* ---------- Base ---------- */

:root {
    color-scheme: dark;

    --bg: #0d1117;
    --surface: #161b22;
    --surface-hover: #1c2128;
    --surface-light: #21262d;

    --border: #30363d;
    --border-light: #3d444d;

    --text: #e6edf3;
    --text-muted: #8b949e;

    --accent: #58a6ff;
    --accent-hover: #79c0ff;

    --success: #3fb950;

    --radius: 8px;
}

* {
    box-sizing: border-box;
}

html {
    background: var(--bg);
}

body {
    max-width: 900px;
    margin: 0 auto;
    padding: 48px 32px 80px;

    background: var(--bg);
    color: var(--text);

    font-family:
        -apple-system,
        BlinkMacSystemFont,
        "Segoe UI",
        Helvetica,
        Arial,
        sans-serif;

    font-size: 16px;
    line-height: 1.7;
}


/* ---------- Typography ---------- */

h1,
h2,
h3,
h4 {
    color: #f0f6fc;
    line-height: 1.25;
    margin-top: 1.8em;
    margin-bottom: 0.7em;
}

h1 {
    font-size: 2.1rem;
    margin-top: 20px;
    padding-bottom: 16px;
    border-bottom: 1px solid var(--border);
}

h2 {
    font-size: 1.5rem;
}

h3 {
    font-size: 1.2rem;
}

p {
    margin: 1em 0;
}

a {
    color: var(--accent);
    text-decoration: none;
}

a:hover {
    color: var(--accent-hover);
    text-decoration: underline;
}

strong {
    color: #f0f6fc;
}


/* ---------- Lesson ---------- */

#lesson {
    margin-top: 28px;
    margin-bottom: 56px;
}

#lesson ul,
#lesson ol {
    padding-left: 28px;
}

#lesson li {
    margin: 6px 0;
}

#lesson code {
    padding: 2px 6px;

    background: var(--surface-light);
    border: 1px solid var(--border);
    border-radius: 5px;

    font-family: "SFMono-Regular", Consolas, monospace;
    font-size: 0.9em;
}

#lesson pre {
    overflow-x: auto;
    padding: 18px;

    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius);
}

#lesson pre code {
    padding: 0;
    background: none;
    border: none;
}


/* ---------- Quotes / lesson intro ---------- */

blockquote {
    margin: 24px 0;
    padding: 14px 20px;

    background: rgba(88, 166, 255, 0.06);
    border-left: 4px solid var(--accent);
    border-radius: 0 var(--radius) var(--radius) 0;

    color: #b7c1cb;
}

blockquote p {
    margin: 0;
}


/* ---------- Completion status ---------- */

#isCompleteSpan {
    display: block;

    padding: 12px 16px;
    margin-bottom: 24px;

    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius);

    color: var(--text-muted);
    font-size: 0.9rem;
}


/* ---------- Buttons ---------- */

button {
    padding: 8px 14px;

    border: 1px solid #388bfd;
    border-radius: 6px;

    background: #1f6feb;
    color: white;

    font: inherit;
    font-weight: 600;

    cursor: pointer;

    transition:
        background 0.15s ease,
        border-color 0.15s ease,
        transform 0.05s ease;
}

button:hover {
    background: #388bfd;
}

button:active {
    transform: translateY(1px);
}

button:disabled {
    opacity: 0.55;
    cursor: not-allowed;
}


/* ---------- Chat ---------- */

.chat-header {
    margin-top: 48px;
    padding: 18px 20px;

    background: var(--surface);
    border: 1px solid var(--border);
    border-bottom: none;

    border-radius: 10px 10px 0 0;
}

.chat-title {
    color: #f0f6fc;
    font-size: 1.05rem;
    font-weight: 650;
}

.chat-subtitle {
    margin-top: 3px;

    color: var(--text-muted);
    font-size: 0.85rem;
}


/* ---------- Chat messages ---------- */

.chat-messages {
    display: flex;
    flex-direction: column;
    gap: 14px;

    min-height: 100px;
    padding: 20px;

    background: #0f141a;

    border-left: 1px solid var(--border);
    border-right: 1px solid var(--border);
}

.message {
    display: flex;
}

.message.user {
    justify-content: flex-end;
}

.message.assistant {
    justify-content: flex-start;
}

.message-bubble {
    max-width: 78%;
    padding: 11px 15px;

    border-radius: 10px;

    line-height: 1.55;
}

.message.user .message-bubble {
    background: #1f6feb;
    color: white;

    border-bottom-right-radius: 3px;
}

.message.assistant .message-bubble {
    background: var(--surface-light);
    border: 1px solid var(--border);

    color: var(--text);

    border-bottom-left-radius: 3px;
}

.message-bubble p:first-child {
    margin-top: 0;
}

.message-bubble p:last-child {
    margin-bottom: 0;
}

.message-bubble pre {
    overflow-x: auto;

    padding: 12px;

    background: var(--bg);
    border-radius: 6px;
}


/* ---------- Chat input ---------- */

.chat-input-area {
    display: flex;
    gap: 10px;
    align-items: flex-end;

    padding: 14px;

    background: var(--surface);

    border: 1px solid var(--border);
    border-radius: 0 0 10px 10px;
}

#chatInput {
    flex: 1;

    width: 100%;
    min-height: 44px;
    max-height: 140px;

    padding: 11px 13px;

    resize: none;

    background: var(--bg);
    color: var(--text);

    border: 1px solid var(--border-light);
    border-radius: 7px;

    font: inherit;
    line-height: 1.4;

    outline: none;
}

#chatInput::placeholder {
    color: #6e7681;
}

#chatInput:focus {
    border-color: var(--accent);

    box-shadow:
        0 0 0 3px rgba(88, 166, 255, 0.12);
}

#sendButton {
    min-width: 80px;
    height: 44px;
}


/* ---------- Selection ---------- */

::selection {
    background: rgba(88, 166, 255, 0.35);
}


/* ---------- Scrollbar ---------- */

::-webkit-scrollbar {
    width: 10px;
    height: 10px;
}

::-webkit-scrollbar-track {
    background: var(--bg);
}

::-webkit-scrollbar-thumb {
    background: #30363d;
    border-radius: 10px;
    border: 2px solid var(--bg);
}

::-webkit-scrollbar-thumb:hover {
    background: #484f58;
}


/* ---------- Mobile ---------- */

@media (max-width: 650px) {
    body {
        padding: 24px 18px 48px;
    }

    h1 {
        font-size: 1.7rem;
    }

    .message-bubble {
        max-width: 90%;
    }

    .chat-input-area {
        align-items: stretch;
    }
}
"""