
codex:
  use_codex: false
  codex_executable_path: /root/.local/bin/codex

openapi_api:
    #eg. http://localhost:11434/v1/chat/completions
  url: http://host.docker.internal:11434/v1/chat/completions
    #eg. gemma4:e2b
  model: gemma4:e2b
    #The authorization should just contain the API key if there is one
  authorization: none
  #streaming kind of works and only for chat
  # line_by_line or streaming
  output_mode: line_by_line


