codex_executable_path: /root/.local/bin/codex
openapi_api_key: newkey
openapi_api_model: gemma4:e2b
openapi_api_output_mode: line_by_line
openapi_api_url: http://pc.dan:11434/v1/chat/completions
openapi_auth_type: body
use_codex: False
